#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
title: Human x Tech
# Short bio or description (displayed in the header)
description: A blog about the scope and significance of the field of digital humanities by a wide-eyed Communication major.

#
# !! DON'T EDIT BELOW THIS MESSAGE
#
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-remote-theme

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
remote_theme: pages-themes/merlot@v0.2.0
